### PR TITLE
Adding Post icons and fixing up icons responsiveness in mumble

### PR DESCRIPTION
**Pull request by ghost**
### Well detailed description of the change :

     I worked on the adding post options for updating and deleting if you are the author and unfollowing and other things if you are not.

#

### Context of the change :

     - Why is this change required ?
     - https://github.com/PraveenMalethia/mumble-vue/issues/41
 

- Does it solve a problem ? (please link the issue)
 
#

### Type of change :

- [ ] Bug fix

- [x] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Preview (Screenshots) :

<p align="center">If it is possible, please link screenshots of your changes preview !
</p>

#

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All new and existing tests passed.

#

### Reviewers

@PraveenMalethia

### CODE REVIEW

**Comment by ghost** [comment]
@PraveenMalethia there is one problem if I remumble a mumble then I am getting options of updating and deleting. Can you change the if statement so it does not show creating and updating even if I remumble it?

**Comment by ghost** [comment]
Also the @click function in anywhere in the post component does not work for some reason

**Comment by PraveenMalethia** [comment]
> @PraveenMalethia there is one problem if I remumble a mumble then I am getting options of updating and deleting. Can you change the if statement so it does not show creating and updating even if I remumble it?

yep i will fix that !

**Comment by PraveenMalethia** [comment]
> @PraveenMalethia there is one problem if I remumble a mumble then I am getting options of updating and deleting. Can you change the if statement so it does not show creating and updating even if I remumble it?

now its showing the correct options for any post !

**Comment by ghost** [comment]
Great, I changed the bg-colour as it was showing gray bg-200 even for dark mode.

**Review by PraveenMalethia — APPROVED** [review]

**Pull request merged**
