### PR TITLE
Adding loading to posts

### PR DESCRIPTION
**Pull request by ghost**
### Well detailed description of the change :

     I made the skeleton loader for the posts.

#

### Context of the change :

     - Why is this change required ?
     - So that there is no empty space when the posts are loading
 

- Does it solve a problem ? (please link the issue)
 https://github.com/PraveenMalethia/mumble-vue/issues/18

#

### Type of change :

- [x] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Preview (Screenshots) :

<p align="center">If it is possible, please link screenshots of your changes preview !
</p>

#

### Checklist:

- [ s
- [x] I have read the **CONTRIBUTING** document.
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All new and existing tests passed.

#

### Reviewers

@PraveenMalethia

### CODE REVIEW

**Comment by PraveenMalethia** [comment]
Can you also add these at the bottom of loading screen !
image

**Comment by ghost** [comment]
Sure, il do it tomorrow!

**Comment by ghost** [comment]
@PraveenMalethia I added the bottom parts on the loading component!

**Comment by PraveenMalethia** [comment]
sure i will check

**Pull request merged**
