### PR TITLE
User detail Page

### PR DESCRIPTION
**Pull request by ghost**
I created the user detail page with the route '/user/<username>'. For now I have made it so that the username that is entered in the route is displayed under a static profile picture. Only the username is dynamic.

### CODE REVIEW

**Comment by PraveenMalethia** [comment]
Can you also add the remumbled thing?

like this 
`dennis remumbled`

image

**Comment by PraveenMalethia** [comment]
and also Posts are not showing in the Small screen 

image

**Comment by ghost** [comment]
@PraveenMalethia  Sure il add the remumbled thing, but also I had a doubt, on small screens should I show the posts as well? Wont it become to conjusted? Or on small screens should I hide the user information and show only the posts?

**Comment by PraveenMalethia** [comment]
@srikarkandula  At the top shows the profile and then posts!

**Comment by ghost** [comment]
Ok will do that and finish by today

**Comment by ghost** [comment]
@PraveenMalethia changed the layout on small screens!

**Pull request merged**
