### PR TITLE
Creating sidenavbar for small screens

### PR DESCRIPTION
**Pull request by ghost**
### Well detailed description of the change :

     I worked on the sidebar for small screens
#

### Context of the change :

     - Why is this change required ?
 

- Does it solve a problem ? (please link the issue)
 https://github.com/PraveenMalethia/mumble-vue/issues/23
#

### Type of change :

- [ ] Bug fix

- [ ] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Preview (Screenshots) :

<p align="center">If it is possible, please link screenshots of your changes preview !
</p>

#

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All new and existing tests passed.

#

### Reviewers

@PraveenMalethia

### CODE REVIEW

**Comment by PraveenMalethia** [comment]
Awesome man ! 
But here is little things if you can do ?

image

The links are at very right side on small screens ! can you fix that ?

**Comment by ghost** [comment]
Ya il change it, just need to reduce the margin-left on small screens

**Comment by ghost** [comment]
@PraveenMalethia done!

**Comment by PraveenMalethia** [comment]
> @PraveenMalethia done!

Awesome ! thankyou , i'll look at that !

**Pull request merged**
